version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/env/app
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    dns: 8.8.8.8
    ports:
      - "8020:80"
      - "8080:8080"
      - "3000:3000"
    environment:
      NODE_ENV: development